### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stop' of null in the sample page

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#1172]
## Browser affected
Chrome M72 / M73

## Description
Screen capture test page has uncaught exception after stopping the screen capture has been ended.

## Steps to reproduce
Go to the test page https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
Click on "Start screen capture"
Click on "Stop screen capture"
Inspect the javascript console for errors.

## Expected results
Screen capture test page should not have any javascript error.

## Actual results

    main.js:108 Uncaught TypeError: Cannot read property 'stop' of null
    at HTMLElement._stopCapturing (main.js:108)
    at MediaStream.stream.addEventListener.e (main.js:90)

**Comment by rantonysamy** [comment]
@ErikHellman @KaptenJansson

**Comment by luanraithz** [comment]
I think it happens because the [`_stopCapturing`](https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/getdisplaymedia/js/main.js#L101) function is called twice, once at the [button's click event](https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/getdisplaymedia/js/main.js#L57), and once at [ stream's event "inactive"](https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/getdisplaymedia/js/main.js#L90). Which one is wrong? Maybe `_stopCapturing` could check if it is null, so the remaining code doesn't have any chance to break.

**Comment by fippo** [comment]
the getDisplayMedia sample no longer uses a peerconnection so this has been overtaken by events
