### ISSUE TITLE
run example

### ISSUE THREAD

**Issue by alicera** [webrtc/samples#1339]
how to run the all example ?
thanks

**Comment by TechnicolorTheClown** [comment]
同问直接放上去运行

**Comment by TechnicolorTheClown** [comment]
同问

**Comment by TechnicolorTheClown** [comment]
1.源码直接放在Nginx上运行，能出现页面，但是在开启摄像头的时候会无效
2.编译 npm install 会出错希望博主能对小白友好点

**Comment by TechnicolorTheClown** [comment]
同问
1.源码直接放在Nginx上运行，能出现页面，但是在开启摄像头的时候会无效
2.编译npm install会出错   
希望博主能对小白友好点

**Comment by udexon** [comment]
I solved the problem on running this:

https://github.com/webrtc/samples/blob/gh-pages/src/content/capture/canvas-record/index.html

This is due to relative path problem in `init()` in `demo.js`:

https://github.com/webrtc/samples/blob/gh-pages/src/js/third_party/webgl_teapot/demo.js

```js
function init() {
    gl.enable(gl.DEPTH_TEST);
    // Can use this to make the background opaque
    // gl.clearColor(0.3, 0.2, 0.2, 1.);
    gl.clearColor(0.0, 0.0, 0.0, 0.0);
    initTeapot();
    initShaders();
    // g_bumpTexture = loadTexture("/samples/src/js/third_party/webgl_teapot/images/bump.jpg");
    // g_envTexture = loadCubeMap("/samples/src/js/third_party/webgl_teapot/images/skybox", "jpg");
    g_bumpTexture = loadTexture("../../../js/third_party/webgl_teapot/images/bump.jpg");
    g_envTexture = loadCubeMap("../../../js/third_party/webgl_teapot/images/skybox", "jpg");
    draw();
}
```

You are welcome!!

**Comment by duqich** [comment]
$ npm install http-server -g
$ npm run start
