### ISSUE TITLE
Is `bufferedamountlow` still buggy?

### ISSUE THREAD

**Issue by edzis** [webrtc/samples#1432]
Is this workaround (last edited 3 years ago) still relevant or can new implementations rely on `bufferedamountlow`?

https://github.com/webrtc/samples/blob/2cad23c099ce290e5634c856ae1a9ebb8012ba16/src/content/datachannel/datatransfer/js/main.js#L117-L118

**Comment by lgrahl** [comment]
Most likely still an issue.

Somewhat tied to https://github.com/sctplab/usrsctp/issues/518. Not exactly though since, IIRC browsers need to accumulate the buffer value (even if the data is already being sent on the network thread) until the JS function yields back to the event loop. What it's currently doing is to race with the network thread. Hence the workaround.

**Comment by alvestrand** [comment]
with the switch to dcsctp, bufferedamountlow should be unbuggy now.
If not, file a bug in bugs.webrtc.org
