### ISSUE TITLE
audio only sample does not work!

### ISSUE THREAD

**Issue by jamieduk** [webrtc/samples#1480]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by jamieduk** [comment]
it dont work!

**Comment by hthetiot** [comment]
Works perfectly for me using Chrome 93.0.4577.82

URL: https://webrtc.github.io/samples/src/content/getusermedia/audio/

@jamieduk you need to provide more information such as your browser version and environment. The lack of audio feedback can be due that auto play fail on the audio tag or that your default microphone is muted. Finally the least you can do is report properly because simply entering the title for filling an issue with a exclamation at the end and comment without more information will not help your issue to be fixed and is disrespectful to the maintainer.

**Comment by AndrewMeadows** [comment]
I thought maybe this issue was talking about the bug I was experiencing with the **insertable-streams/audio-processing** example however @jamieduk did not supply enough information for me to confirm.  So I created [issue-1483](https://github.com/webrtc/samples/issues/1483) to track my problem.
