### ISSUE TITLE
Filetransfer - Allow to send files more than once without reload

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#485]
Currently it allows you to send file once without reloading the page. It would be nice if it allows you to send another file without reloading the page.

http://webrtc.github.io/samples/src/content/datachannel/filetransfer/

**Comment by samdutton** [comment]
+1

Just thinking the same.

@fippo

**Comment by fippo** [comment]
+1 -- it's pretty easy to do but the actual behaviour is worth discussing.

I assume that using single peerconnection and separate datachannel for each file is the approach that works best for the SCTP layer -- @juberti @jiayliu?

Since separate datachannels require a better ondatachannel, shall we show how to use the datachannels protocol field? We don't really use multiple protocols but I assume doing so will get people thinking about why that is a good idea.

Do we offer multiple files for download?

Do we remove files that have beeen downloaded? Showing the use of URL.revokeObjectURL would be a good, I currently have a out-of-memory crash issue open with this demo :-)

**Comment by juberti** [comment]
I think keeping the demo as simple as possible is the right way to go. IOW, blow away all previous state when the "restart" or whatever button is pressed.

**Comment by fippo** [comment]
makes sense. Maybe add an advanced demo at some point in the future.
