### ISSUE TITLE
webkitGetUserMedia adapter fails in WebKit browsers other than Chrome

### ISSUE THREAD

**Issue by lquinn** [webrtc/samples#591]
The demo at https://webrtc.github.io/samples/src/content/getusermedia/gum/ fails right now on BlackBerry 10 devices because the JavaScript assumes that Chrome is the only WebKit-based browser that supports navigator.webkitGetUserMedia:

```javascript
} else if (navigator.webkitGetUserMedia) {
  webrtcUtils.log('This appears to be Chrome');

  webrtcDetectedBrowser = 'chrome';

  // the detected chrome version.
  webrtcDetectedVersion =
    parseInt(navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)[2], 10);
```

A TypeError is thrown because "Chrom(e|ium)" does not appear in the BB10 User-Agent.

The sample works on BlackBerry 10.3.2 when I use Web Inspector to override the User-Agent and masquerade as Chrome.

Could we make webrtcDetectedVersion a bit more robust? There are other WebKit-based browsers out there that would probably trip over this too.

**Comment by KaptenJansson** [comment]
@lquinn What browser does BlackBerry use?

The reason we need to know the version of the browser (in addition to what browser is used) is that we need to shim different things because WebRTC and the Javascript api's are still under development and browsers have several release channels hence old and new API's do exists alongside each other for quite some time in the ecosystem.

Also worth noting is that just because a browser use WebKit/Blink does not mean it has implemented all the necessary WebRTC javascript API's, this can be tricky to determine without lots of specific logic per browser.

But having said that, I do support the notion of supporting more browsers, it's just that we have been focusing on the largest ones so far.

By the way this bug belongs in https://github.com/webrtc/adapter repo as all the demos use adapter.js to shim said browser differences.

**Comment by KaptenJansson** [comment]
Could you re-file this is issue in the https://github.com/webrtc/adapter repo so you can follow progress?

**Comment by samdutton** [comment]
The BlackBerry browser is WebKit based.

BlackBerry accounts for only around 0.33% of browser traffic (according to
StatCounter
<http://gs.statcounter.com/#all-browser-ww-monthly-200807-201507>) but I
agree that adapter.js should cope with non-Chrome WebKit browsers.

**Comment by lquinn** [comment]
Re-filed as https://github.com/webrtc/adapter/issues/94. Thanks for the quick feedback!
