### ISSUE TITLE
Add desktop capture demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#595]
We should add a demo utilizing the desktop capture extension in the repo.

**Comment by fippo** [comment]
some notes about testing this since I was just playing around with that for talky and spent some time figuring out command line flag issues:
```
        //.addArguments('use-fake-device-for-media-stream')
        //.addArguments('use-fake-ui-for-media-stream')
        .addArguments('load-and-launch-app=/home/fippo/talky-extension')
        .addArguments('auto-select-desktop-capture-source=Entire screen');
```
1) It doesn't work with the fake devices (see [here](https://code.google.com/p/chromium/issues/detail?id=459532#c15) -- not a big deal for the sample since it doesn't need to show both camera and desktop)
2) this needs the load-and-launch-app with the path to the extension
3) Don't use extra quotes around "Entire screen" in the auto-select-desktop-capture-source.  Also make sure that process.env.LANGUAGE is set to 'en'.

**Comment by jan-ivar** [comment]
Any interest in trying to do this cross-browser? Firefox [has this as well](https://mozilla.github.io/webrtc-landing/gum_test.html), though sadly this isn't standardized well yet.

**Comment by fippo** [comment]
another issue: chrome doesn't think that file:// is a secure url. Possibly it can ignore this check iff the auto-select-desktop-capture-source is present?

**Comment by KaptenJansson** [comment]
> another issue: chrome doesn't think that file:// is a secure url. Possibly it can ignore this check iff the auto-select-desktop-capture-source is present?

`--allow-file-access-from-files` should solve that.

**Comment by fippo** [comment]
@jan-ivar Firefox testing would be easier if https://bugzilla.mozilla.org/show_bug.cgi?id=1184331 was fixed :-)

**Comment by dgsplayer** [comment]
The option auto-select-desktop-capture-source='Entire screen' works very well
But how do I make it work in other languages?

**Comment by KaptenJansson** [comment]
Closing due to age.

**Comment by alex-eri** [comment]
> it work in other languages

Did you found solution?

**Comment by alvestrand** [comment]
Since the use of desktop capture extensions is recommended against and should be unnecessary, this won't get any further updates.
