### ISSUE TITLE
user can send "empty" text 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#678]
Steps to reproduce:
1. Go to https://webrtc.github.io/samples/src/content/datachannel/basic/
2. Click on "Start" to send text
3. Without entering anything, click "Send"

Actual results:
The user is able to 'Send' "empty" text

Expected results:
The "Send" button should be disabled till the user starts to enter some text in the Send box

**Comment by tednakamura** [comment]
From a testing perspective, I like that we can currently "send" empty text. However, I agree with the general idea that a real application would most likely include client side logic to prevent such empty submissions.

Since we use that page pretty frequently for testing, I prefer to leave it unchanged.

**Comment by KaptenJansson** [comment]
I agree with the last comment.
