### ISSUE TITLE
Hangup button enabled when getuserMedia fails

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#719]
Device: Celes
Version: 49.0.2577.0 swv / 7692.0.0
![img_7565](https://cloud.githubusercontent.com/assets/15255941/11944911/e46351ba-a7fe-11e5-9aba-3bb58e7cf8d4.JPG)
![img_7568](https://cloud.githubusercontent.com/assets/15255941/11944912/e7bd372c-a7fe-11e5-8c36-9aeabdc34299.JPG)

Repro steps:
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/audio/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click on 'Call' for default codec "Opus"
4. Observe a pop-up error dialog box with message "getUserMedia() error: PermissionDeniedError"
(Please see attached screenshot) even though page is loaded on https. There are no errors in javascript console logs.
5. Click 'Ok' on the above error dialog box to continue and hangup the call
6. Click on "Hangup"
7. Observe "Uncaught TypeError: Cannot read property 'getTracks' of undefined" in javascript logs.

Expected result:
1.  Clicking on 'Call" on page https://webrtc.github.io/samples/src/content/peerconnection/audio/ should place the call successfully

Actual result:
1. Clicking on 'Call" on page https://webrtc.github.io/samples/src/content/peerconnection/audio/ is throwing an error dialog box with message "getUserMedia() error: PermissionDeniedError"
2. Dropdown for codec is disabled and hanging up the call is throwing an error " "Uncaught TypeError: Cannot read property 'getTracks' of undefined"

Javscript logs:

"This appears to be Chrome
common.js:8 4.075: Starting call
common.js:8 4.080: Created local peer connection object pc1
common.js:8 4.084: Created remote peer connection object pc2
common.js:8 4.089: Requesting local stream
adapter.js:32 chrome: {"audio":true,"video":false}
common.js:8 272.451: Ending call
main.js:115 Uncaught TypeError: Cannot read property 'getTracks' of undefinedhangup @ main.js:115"

**Comment by cvranjani** [comment]
Looks like there is a problem with some of the github pages involving getusermedia also.

Javascript logs shows "getUserMedia error:  NavigatorUserMediaError {}" upon opening Github sample pages like  https://webrtc.github.io/samples/src/content/getusermedia/audio, https://webrtc.github.io/samples/src/content/getusermedia/volume 

"This appears to be Chrome
adapter.js:32 chrome: {"audio":true,"video":false}
main.js:52 navigator.getUserMedia error:  NavigatorUserMediaError {}"

**Comment by KaptenJansson** [comment]
All those pages work for me, they haven't changed for a while.

This looks you have denied permissions to the https://webrtc.github.io domain. Could you check that you have not blocked permissions for said domain? Either by checking your media permissions or using a different account (permissions are synced across devices in your Chrome account)

WRT to the getTracks error, it happens due to getUserMedia have not succeeded thus not receiving a media stream and we try to shut down. We should improve the logic here (do not call on getTracks if a  media stream does not exist when shutting down).

**Comment by fippo** [comment]
@KaptenJansson the hangup button shouldn't be enabled when getUserMedia fails. This is a problem across the board I think. To reproduce block the camera using the camera icon at the right of the address bar.

I wonder if we can test permission denied scenarios using selenium. Are those permissions stored as part of the profile? Starting with a fresh profile and blocking permissions seems to add this to Default/Preferences:

```
"media_stream_camera":{"https://webrtc.github.io:443,*":{"setting":2}},"media_stream_mic":{}
```

Maybe @phoglund knows (and is happy if we don't need extra command line flags!)

Digging further this seems to be stored like this in the JSON:

```
profile:
  avatar_bubble_tutorial_shown: 2
  avatar_index:                 26
  content_settings:
    exceptions:
[...]
      media_stream_camera:
        https://talky.io:443,*:
          last_used: 1450772896.477158
          setting:   1
        https://webrtc.github.io:443,*:
          setting: 2
      media_stream_mic:
        https://talky.io:443,*:
          last_used: 1450772896.477131
          setting:   1
```

I allowed on talky.io (setting => 1) but blocked on webrtc.github.io (setting => 2)

Using new chrome.Options().setUserPreferences blocks the camera but fake devices bypass that check. Might still be useful for testing on devices with physical hardware.

**Comment by KaptenJansson** [comment]
AFAIK all permissions (some exceptions might exist) are stored in your Chrome profile, and if you enabled sync, it's propagated to all devices with sync enabled.

Regarding fake devices bypassing the check, I think this is because we are serving the pages as files in Webdriver rather than from a server. So if we served the pages over a server instead it should be possible (the other flags only enables the fake device and bypasses the permission UI(which should not affect existing permissions set in the profile))

**Comment by cvranjani** [comment]
All the sample pages mentioned in the initial bug report are working as expected now. Permissions for  https://webrtc.github.io/ are in "Allow" state when I filed the bug. Not sure what caused the issue initially.

Leaving this bug in "Open" state to track the other issue "Hangup button enabled when getuserMedia fails"
