### ISSUE TITLE
Transfer file to my peer connection

### ISSUE THREAD

**Issue by abhilashpullelil** [webrtc/samples#760]
**Any**

**How can I share my uploaded file to my peer connection? In the demo, you just send and receive on same browser.**

**Comment by cilphex** [comment]
I'm wondering the same thing. The demos are not helpful.

**Comment by samdutton** [comment]
This demo shows how to create a peer connection and use Data Channels to
share files.

It's not intended to show the whole process of setting up a call between
two separate browser endpoints. Doing that would make the demo more complex
— since much of the code would be about setting up the call — and would, of
course, mean the demo couldn't be run within a single page.

If you want to learn the process of sharing a file between two endpoints, I
suggest going through the Google I/O 2014 file sharing codelab
http://io2014codelabs.appspot.com/static/codelabs/webrtc-file-sharing/#1.
It's a couple of years old but mostly still relevant. (We'll be working on
a new version shortly.)

To find out more about setting up a call between two endpoints, take a look
at github.com/apprtc: the code behind appr.tc. For more resources, try
webrtc.org/start.

Hope that helps!

**Comment by cilphex** [comment]
The demo can be run in a single page. Leaving out the signaling step makes all these demos so confusing, because it's not clear how they find each other, and which code belongs to what side.

I understand that covering that is outside the scope of what you're trying to achieve here, but having it would add so much clarity.

You can use Firebase for a signaling server very easily, and probably for free.

I've done some studying and have made my own single-page app that uses webrtc, so I know it's possible: https://github.com/cilphex/dropkick.

Anyway, just feedback on the demos at large I guess.

**Comment by samdutton** [comment]
Hi @cilphex — thanks for the suggestion. I take your point that, without signalling, it's tricky to understand how these demos can be applied to a real application.

@KaptenJansson @juberti It might be good to have a 'barebones' version of [github.com/apprtc](https://github.com/apprtc), maybe (as @cilphex suggests) using Firebase for signaling. I'm working on updating the WebRTC codelab — that might be a good starting point.

**Comment by KaptenJansson** [comment]
Yes that makes sense to me, like a single plage signalling demo. Contributions are welcome ;)

**Comment by fippo** [comment]
@jan-ivar has a funky examples of signaling that uses localStorage. That could be used to mock a signaling service without creating a depedency on something proprietary

**Comment by jan-ivar** [comment]
https://jsfiddle.net/jib1/2v1Lnpmx/
