### ISSUE TITLE
Selecting output device based on OS device ID

### ISSUE THREAD

**Issue by javess-zz** [webrtc/samples#761]
I have an application that will pass a OS level device id as a GET parameter to a local running page. Is there any way to tie back that device id to any of the devices yielded by enumerateDevices? 

Imagine I wanted to set the dropdown https://webrtc.github.io/samples/src/content/devices/multi/ to default to whatever device I passed in. 

Sorry in advance if this is not the right place for this question

**Comment by KaptenJansson** [comment]
Hi,

No, the deviceID from enumerate devices is a generated one. It's by design. What you can do however is if you can figure the device name, you can check the device label (it should have the same name as the device in the OS) and use the device id for said device. Do note that getUserMedia permissions must be given in order for the device label to be populated.
