### ISSUE TITLE
Not readable error on chrome for android

### ISSUE THREAD

**Issue by ghost** [webrtc/samples#922]
**Browsers and versions affected**
Chrome on android , version 59

**Description**
Getusermedia () fails with Error: Not Readable Error

**Steps to reproduce**

https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Expected results**
Capture the webcam video

**Actual results**
Error: Not Readable Error

I have checked the permissions....webcam and microphone are allowed access.
It works on desktop chrome, only chrome on android fails.

**Comment by voiceactivity** [comment]
Having the same issue. 
Firefox for Android works perfectly 👍 
Also noticed that the Firefox on Android offers me the choice of camera I want to use (front or rear). 
Chrome remains silent and just throws the 'Not Readable Error' on attempt to getUserMedia call even 
though  all permissions granted.
Would be nice to have that one fixed.
Thank you.

**Comment by voiceactivity** [comment]
Oops, looks like this bug is related to the Chromium rather than to the adapter.js

In nutshell, as per guidou@chromium.org:
**_"If the camera does not report a frame rate of at least 1fps, it will be rejected in M58 and later.
The --enable-features=MediaStreamOldVideoConstraints switch makes 59 and 60 work like 58, so it will not work in this case.
Since this is not the first bug related to cameras that report incorrect frame rates, I think we should patch Chrome to be less strict about that.
Let's keep this bug open and I'll prepare a patch to fix this in 62.
If the patch is simple enough, maybe we'll be able to merge to 61."_**

For all who are interested: https://bugs.chromium.org/p/chromium/issues/detail?id=739953&q=getUserMedia&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by ghost** [comment]
I raised it as bug in chrome for android and It seems to have been fixed now. I checked in chrome for android version 61.0.3163.98 and it works . Hurray !

**Comment by RamyaAshika** [comment]
Hey I'm facing the same issue..Any updates on this?

**Comment by sreenivaskavali** [comment]
This problem will occur mostly if the camera was used by another application.
or 

If it is not destroyed in the previous usage.
